server:
  port: 8080

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.64.137:3306/cloud2021?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: dcim
    password: Dcim@2020
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 600000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      # validation-query: SELECT 1 FROM DUAL
      # filter: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=500

#mybatis的相关配置
mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mytest.boot.bean
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#server:
#  port: 8888
#  error:
#    path: /error
#
#car:
#  name: BYD
#  price: 100000.0
#
#person:
#  userName: zhangsan
#  boss: true
#  birth: 2019/12/9
#  age: 18
#  interests:
#    - 篮球
#    - 足球
#  animal: [dog, cat, pig]
#  scores: {chinese: 100, english: 80}
#  salaries: [10000.0, 11000.0]
#  allPets:
#    sick:
#      - {name: dog}
#      - {name: cat}
#    health:
#      - {name: pig}

#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations:
#        - classpath:/haha/
#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#    view:
#      suffix: .html

